import logging

import httpx

from app.classifier import TriageResult
from app.config import settings
from app.models import TriageCategory

logger = logging.getLogger(__name__)

CATEGORY_LABELS = {
    TriageCategory.SIMPLE_BUMP: "simple-bump",
    TriageCategory.BREAKING_CHANGE: "breaking-change",
    TriageCategory.NO_FIX: "no-fix",
}

SEVERITY_LABELS = {
    "critical": "severity:critical",
    "high": "severity:high",
    "moderate": "severity:medium",
    "medium": "severity:medium",
    "low": "severity:low",
}

ISSUE_BODY_TEMPLATE = """## ⚠️ Security Vulnerability — No Fix Available: {package_name} ({severity})

**CVE(s):** {cve_ids}
**Package:** {package_name} ({ecosystem})
**Fixed in:** {fix_version}
**Advisory:** {advisory_url}

### Why This Needs Human Review
No patched version is available for this vulnerability. Automated remediation is not possible.

### Recommended Action
{recommended_action}

### Next Steps
- [ ] Assess exposure in the codebase
- [ ] Evaluate alternative packages or workarounds
- [ ] Determine if the dependency can be removed
- [ ] Accept risk or implement mitigation

---
*Auto-generated by devin-vuln-triage — escalated because no automated fix exists*
"""


async def ensure_labels_exist(repo: str) -> None:
    """Create required labels on the target repo if they don't exist."""
    labels_to_create = [
        ("security-alert", "d73a4a", "Security vulnerability alert"),
        ("simple-bump", "0e8a16", "Simple version bump fix"),
        ("breaking-change", "fbca04", "Fix requires major version upgrade"),
        ("no-fix", "b60205", "No fix version available"),
        ("severity:critical", "b60205", "Critical severity"),
        ("severity:high", "d93f0b", "High severity"),
        ("severity:medium", "e4e669", "Medium severity"),
        ("severity:low", "0e8a16", "Low severity"),
    ]
    headers = {
        "Authorization": f"token {settings.github_token}",
        "Accept": "application/vnd.github+json",
    }
    async with httpx.AsyncClient(timeout=15) as client:
        for name, color, description in labels_to_create:
            resp = await client.post(
                f"https://api.github.com/repos/{repo}/labels",
                headers=headers,
                json={"name": name, "color": color, "description": description},
            )
            if resp.status_code == 422:
                pass  # label already exists
            elif resp.status_code >= 400:
                logger.warning("Failed to create label %s: %s", name, resp.text)


async def create_tracking_issue(triage: TriageResult, repo: str) -> dict:
    """Create a GitHub Issue in the target repo for this vulnerability.

    Returns {"number": int, "url": str} or raises on failure.
    """
    cve_str = ", ".join(triage.cve_ids) if triage.cve_ids else "N/A"
    title = (
        f"[Needs Human Review] Security: {triage.package_name} — "
        f"{cve_str} ({triage.severity})"
    )
    body = ISSUE_BODY_TEMPLATE.format(
        package_name=triage.package_name,
        severity=triage.severity,
        cve_ids=cve_str,
        ecosystem=triage.ecosystem,
        fix_version=triage.fix_version or "No fix available",
        advisory_url=triage.advisory_url or "N/A",
        recommended_action=triage.recommended_action,
    )
    labels = ["security-alert", CATEGORY_LABELS.get(triage.category, "")]
    severity_label = SEVERITY_LABELS.get(triage.severity)
    if severity_label:
        labels.append(severity_label)
    labels = [label for label in labels if label]

    headers = {
        "Authorization": f"token {settings.github_token}",
        "Accept": "application/vnd.github+json",
    }
    async with httpx.AsyncClient(timeout=15) as client:
        await ensure_labels_exist(repo)
        resp = await client.post(
            f"https://api.github.com/repos/{repo}/issues",
            headers=headers,
            json={"title": title, "body": body, "labels": labels},
        )
        resp.raise_for_status()
        data = resp.json()
        logger.info("Created issue #%d in %s", data["number"], repo)
        return {"number": data["number"], "url": data["html_url"]}


async def comment_on_issue(repo: str, issue_number: int, body: str) -> None:
    """Add a comment to an existing GitHub Issue."""
    headers = {
        "Authorization": f"token {settings.github_token}",
        "Accept": "application/vnd.github+json",
    }
    async with httpx.AsyncClient(timeout=15) as client:
        resp = await client.post(
            f"https://api.github.com/repos/{repo}/issues/{issue_number}/comments",
            headers=headers,
            json={"body": body},
        )
        resp.raise_for_status()
        logger.info("Commented on issue #%d in %s", issue_number, repo)
